### ISSUE TITLE
Broken on Big Sur

### ISSUE THREAD

**Issue by jason5122** [BlacksunLabs/LockScream#3]
Hi, will this app ever support Big Sur? Currently, the wallpaper does not take up the entire screen and is blurry, and the UI elements are based on earlier versions of macOS and are outdated. Thanks!

**Comment by n0ncetonic** [comment]
I'll have to look at getting Big Sur on a test machine. I've been keeping away from it on my normal machines due to all the errors I've had with it in testing

**Comment by n0ncetonic** [comment]
Apologies for completely ghosting on this issue. I didn't have a test machine to install Big Sur on for some time but I've started tracking progress towards Big Sur support in #4
